### ISSUE TITLE
Namespace overwrite does not work unless the namespace `ashr` is explicitly called

### ISSUE THREAD

**Issue by gaow** [dcgerard/sabotash#1]
Great package -- big help to my research. Just a minor issue though: Namespace overwrite does not seem to work unless the namespace `ashr` is explicitly called. For example, this does not work

```
library(ashr)
library(sabotash)
ash.workhorse
```

But replacing `ash.workhorse` with `ashr::ash.workhorse` works perfectly. Any suggestions?

**Comment by dcgerard** [comment]
Fixed by a00e7f2f04700c27d53e2c1f5abce9ba5f93714f

**Comment by gaow** [comment]
Working great now :+1:  my simulations are up and running! Thanks for the prompt fix.
